Repository cqframework/cqf-ruler, pull requests merged in 2021-06, with the labels that each got.

#277 Add dynamicValue error checking and type conversion
  r4/src/main/java/org/opencds/cqf/r4/providers/ActivityDefinitionApplyProvider.java
  r4/src/main/java/org/opencds/cqf/r4/providers/PlanDefinitionApplyProvider.java
Labels: enhancement

#297 Update tester page to latest hapi version
  cqf-ruler-dstu3/pom.xml
  cqf-ruler-dstu3/src/main/webapp/WEB-INF/templates/tmpl-head.html
  cqf-ruler-dstu3/src/main/webapp/img/favicon.ico
  cqf-ruler-dstu3/src/main/webapp/img/sample-logo.jpg
  cqf-ruler-dstu3/src/main/webapp/js/moment-with-locales.min.js
  cqf-ruler-r4/pom.xml
  cqf-ruler-r4/src/main/webapp/WEB-INF/templates/tmpl-head.html
  cqf-ruler-r4/src/main/webapp/img/favicon.ico
  cqf-ruler-r4/src/main/webapp/img/sample-logo.jpg
  cqf-ruler-r4/src/main/webapp/js/moment-with-locales.min.js
  dstu3/src/main/java/org/opencds/cqf/dstu3/servlet/CdsHooksServlet.java
  pom.xml
  r4/src/main/java/org/opencds/cqf/r4/servlet/CdsHooksServlet.java
  scripts/maintenance.sh
Labels: dependencies

#300 Use HAPI bom for versions, make content size limit larger
  cqf-ruler-dstu3/src/main/webapp/WEB-INF/jetty-web.xml
  cqf-ruler-r4/src/main/webapp/WEB-INF/jetty-web.xml
  pom.xml
Labels: bug, enhancement
